### ISSUE TITLE
Site fedetask can’t be reached

### ISSUE THREAD

**Issue by ToldoDM** [fedetask/pam-tutorials#2]
in your readme there is the link to your site, but it doesn't exists anymore. 
you should update your readme.

**Comment by tyrumus** [comment]
Agreed.

@fedetask 
If there's still a copy of the tutorials somewhere, they should either be copied to a Gist or into the Wiki on this repo. I'd be more than happy to help. :)

**Comment by fedetask** [comment]
Thank you! I updated the readme. Unfortunately at the moment, I don't have the tutorials available as they were hosted on Bluehost + WordPress. I'll try to recover and give them to you.

**Comment by tyrumus** [comment]
That would be awesome. Looking forward!

**Comment by zerom0** [comment]
@fedetask The links in `TutorialsIndex.md` also point to fedetask.com, which seems to be registered to someone else since last year. The new owner redirects you to sites that you didn't want to visit. Therefore I suggest to update or remove TutorialsIndex.md for your own reputation.

Your original articles are still available in the internet archive.
https://web.archive.org/web/20190523222819/https://fedetask.com/write-linux-pam-module/
